version: '3.1'

services:

  db:
    image: mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 20s
       retries: 10

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: kong
